### ISSUE TITLE
Adicionar "define( 'SCRIPT_DEBUG', true );" no tema por padrão.

### ISSUE THREAD

**Issue by Elianuss** [willnv/wp-drift#8]

**Comment by willnv** [comment]
Ligar todos os debugs por padrão na verdade

**Comment by willnv** [comment]
Coloquei 2 funções no theme-config pra ligar o debug/mostrar todos os erros possíveis:
`ini_set( 'display_errors', 'On' );`
`error_reporting( E_ALL );`
não precisa ir no wp-config e ligar o debug mais...
Quando o site estiver sem nenhum erro/notice pode apagar essas linhas ou colocar 'off" no ini_set.

**Comment by willnv** [comment]
debug de script não vai ser ligado, de resto, deu. Fechado.
